export type Sectorial =
  | 'PanOceania'
  | 'Shock Army of Acontecimento'
  | 'Military Orders'
  | 'Neoterran Capitaline Army'
  | 'Varuna Immediate Reaction Division'
  | `Svalarheima's Winter Force`
  | 'Yu Jing'
  | 'Imperial Service'
  | 'Invincible Army'
  | 'Ariadna'
  | 'Caledonian Highlander Army'
  | 'Force de Résponse Rapide Merovingienne'
  | 'USAriadna Ranger Force'
  | 'Tartary Army Corps'
  | 'Haqqislam'
  | 'Qapu Khalqi'
  | 'Ramah Taskforce'
  | 'Nomads'
  | 'Jurisdicitonial Command of Corregidor'
  | 'Jurisdicitonial Command of Bakunin'
  | 'Jurisdicitonial Command of Tunguska'
  | 'Combined Army'
  | 'Morat Agression Force'
  | 'Shasvastii Expeditionary Force'
  | 'Onyx Contact Force'
  | 'ALEPH'
  | 'Steel Phalanx'
  | 'Operations Subsection of the S.S.S.'
  | 'Tohaa'
  | 'Druze Bayram Security'
  | 'Japanese Secessionist Army'
  | 'Ikari Company'
  | 'Starco. Free Company of the Star'
  | 'Spiral Corps'
  | 'Foreign Company'
  | 'Dahshat Company'
  | 'O-12'
  | 'NA-2 Mercenaries';
